apiVersion: v1
kind: Service
metadata:
  name: redis-headless-service
  labels:
    app: redis-headless-service
spec:
  ports:
  - port: 6379
    name: web
  clusterIP: None
  selector:
    app: redis
