apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis-cluster
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - name: tcp6379
    protocol: TCP
    port: 6379
    target: 6379
    nodePort: 31379
  clusterIP: None
  
